config/routes.rb
MyFirstApp::Application.routes.draw do
  
  resources :blocks

  resources :contacts

  get "dashboard/index"

  get "home/index"

  devise_for :users

  root :to => "dashboard#index"

end

app/models/block.rb
class Block < ActiveRecord::Base
  attr_accessible :block_name
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :mobile_number
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
   def after_sign_in_path_for(resource_or_scope)

    # dashboard_index_path
        '#/dashboard'
    # home_index_path
  end
end

app/controllers/blocks_controller.rb
class BlocksController < InheritedResources::Base
  respond_to :json
  layout 'admin'
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
  respond_to :json
  layout 'admin'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    render :layout => 'admin', :nothing => true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :block_name %><br />
    <%= f.text_field :block_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<h1>Listing blocks</h1>

<table>
  <tr>
    <th>Block name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blocks.each do |block| %>
  <tr>
    <td><%= block.block_name %></td>
    <td><%= link_to 'Show', block %></td>
    <td><%= link_to 'Edit', edit_block_path(block) %></td>
    <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Block', new_block_path %>

app/views/blocks/new.html.erb
<h1>New block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Block name:</b>
  <%= @block.block_name %>
</p>


<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :mobile_number %><br />
    <%= f.text_field :mobile_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Mobile number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.mobile_number %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Mobile number:</b>
  <%= @contact.mobile_number %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/home/index.html.erb
<!-- Start: slider -->
<div class="slider">
	<div class="container-fluid">
		<div id="heroSlider" class="carousel slide">
			<div class="carousel-inner">
				<div class="active item">
					<div class="hero-unit">
						<div class="row-fluid">
							<div class="span7 marketting-info">
								<h1>TELL ABOUT YOUR BUSINESS AND CORPORATE.</h1>
								<p>
									We are Bootbusiness and we are awesome.We solve your technology problems by our awesome products.
									We are Bootbusiness and we are awesome.We solve your technology problems by our awesome products.
								</p>
								<h3><a href="product.html" class="btn">Learn more</a></h3>
							</div>
							<div class="span5">
								<!-- <img src="img/placeholder.jpg" class="thumbnail"> -->
								<%= image_tag("placeholder.jpg", :class => "thumbnail")%>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="hero-unit">
						<div class="row-fluid">
							<div class="span7 marketting-info">
								<h1>TELL ABOUT YOUR NATURE OF WORK</h1>
								<p>
									We are Bootbusiness and we design ultimate website applications.
									We are Bootbusiness and we design ultimate website applications.
								</p>
								<h3><a href="service.html" class="btn">Learn more</a></h3>
							</div>
							<div class="span5">
								<!-- <img src="img/placeholder.jpg" class="thumbnail"> -->
								<%= image_tag("placeholder.jpg", :class => "thumbnail")%>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="hero-unit">
						<div class="row-fluid">
							<div class="span7 marketting-info">
								<h1>TELL ABOUT YOUR PRODUCT</h1>
								<p>
									Get excited about our products.We build awesome products in mobile.
									We build awesome products in mobile.We build awesome products in mobile.
								</p>
								<h3><a href="#" class="btn btn-primary">Buy now</a><a href="product.html" class="btn">Learn more</a></h3>
							</div>
							<div class="span5">
								<!-- <img src="img/placeholder.jpg" class="thumbnail"> -->
								<%= image_tag("placeholder.jpg", :class => "thumbnail")%>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="hero-unit">
						<div class="row-fluid">
							<div class="span7 marketting-info">
								<h1>TELL ABOUT YOUR ANOTHER PRODUCT</h1>
								<p>
									Get excited about our products.We build awesome products in mobile.
									We build awesome products in mobile.We build awesome products in mobile.
								</p>
								<h3><a href="#" class="btn btn-primary">Buy now</a><a href="product.html" class="btn">Learn more</a></h3>
							</div>
							<div class="span5">
								<!-- <img src="img/placeholder.jpg" class="thumbnail"> -->
								<%= image_tag("placeholder.jpg", :class => "thumbnail")%>
							</div>
						</div>
					</div>
				</div>
			</div>
			<a class="left carousel-control" href="#heroSlider" data-slide="prev">‹</a>
			<a class="right carousel-control" href="#heroSlider" data-slide="next">›</a>
		</div>
	</div>
</div>
<!-- End: slider -->
<!-- Start: PRODUCT LIST -->
<div class="container">
	<div class="page-header">
		<h2>Our products</h2>
	</div>
	<div class="row-fluid">
		<ul class="thumbnails">
			<li class="span4">
				<div class="thumbnail">
					<!-- <img src="img/placeholder-360x200.jpg" alt="product name"> -->
					<%= image_tag("placeholder-360x200.jpg", :alt => "product name")%>
					<div class="caption">
						<h3>Product name</h3>
						<p>
							Few attractive words about your product.Few attractive words about your product.
							Few attractive words about your product.Few attractive words about your product.
						</p>
					</div>
					<div class="widget-footer">
						<p>
							<a href="#" class="btn btn-primary">Buy now</a>&nbsp; <a href="product.html" class="btn">Read more</a>
						</p>
					</div>
				</div>
			</li>
			<li class="span4">
				<div class="thumbnail">
					<!-- <img src="img/placeholder-360x200.jpg" alt="product name"> -->
					<%= image_tag("placeholder-360x200.jpg", :alt => "product name")%>
					<div class="caption">
						<h3>Product name</h3>
						<p>
							Few attractive words about your product.Few attractive words about your product.
							Few attractive words about your product.Few attractive words about your product.
						</p>
					</div>
					<div class="widget-footer">
						<p>
							<a href="#" class="btn btn-primary">Buy now</a>&nbsp; <a href="product.html" class="btn">Read more</a>
						</p>
					</div>
				</div>
			</li>
			<li class="span4">
				<div class="thumbnail">
					<!-- <img src="img/placeholder-360x200.jpg" alt="product name"> -->
					<%= image_tag("placeholder-360x200.jpg", :alt => "product name")%>
					<div class="caption">
						<h3>Product name</h3>
						<p>
							Few attractive words about your product.Few attractive words about your product.
							Few attractive words about your product.Few attractive words about your product.
						</p>
					</div>
					<div class="widget-footer">
						<p>
							<a href="#" class="btn btn-primary">Buy now</a>&nbsp; <a href="product.html" class="btn">Read more</a>
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
	<div class="page-header">
		<h2>Our Services</h2>
	</div>
	<div class="row-fluid">
		<ul class="thumbnails">
			<li class="span4">
				<div class="thumbnail">
					<!-- <img src="img/placeholder-360x200.jpg" alt="product name"> -->
					<%= image_tag("placeholder-360x200.jpg", :alt => "product name")%>
					<div class="caption">
						<h3>Service title</h3>
						<p>
							Few attractive words about your service.Few attractive words about your service.
							Few attractive words about your service.Few attractive words about your service.
						</p>
					</div>
					<div class="widget-footer">
						<p>
							<a href="#" class="btn btn-primary">Try for free</a>&nbsp; <a href="product.html" class="btn">Read more</a>
						</p>
					</div>
				</div>
			</li>
			<li class="span4">
				<div class="thumbnail">
					<!-- <img src="img/placeholder-360x200.jpg" alt="product name"> -->
					<%= image_tag("placeholder-360x200.jpg", :alt => "product name")%>
					<div class="caption">
						<h3>Service title</h3>
						<p>
							Few attractive words about your service.Few attractive words about your service.
							Few attractive words about your service.Few attractive words about your service.
						</p>
					</div>
					<div class="widget-footer">
						<p>
							<a href="#" class="btn btn-primary">Try for free</a>&nbsp; <a href="product.html" class="btn">Read more</a>
						</p>
					</div>
				</div>
			</li>
			<li class="span4">
				<div class="thumbnail">
					<!-- <img src="img/placeholder-360x200.jpg" alt="product name"> -->
					<%= image_tag("placeholder-360x200.jpg", :alt => "product name")%>
					<div class="caption">
						<h3>Service title</h3>
						<p>
							Few attractive words about your service.Few attractive words about your service.
							Few attractive words about your service.Few attractive words about your service.
						</p>
					</div>
					<div class="widget-footer">
						<p>
							<a href="#" class="btn btn-primary">Try for free</a>&nbsp; <a href="product.html" class="btn">Read more</a>
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
<!-- End: PRODUCT LIST -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html ng-app="contactapp">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Bootbusiness | Short description about company">
		<meta name="author" content="Your name">
		<title>MyFirstApp</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body data-target=".bs-docs-sidebar" data-spy="scroll">
		<%= render :partial => "shared/header" %>

		<!-- Start: MAIN CONTENT -->
		<div class="content">
			<div ng-view></div>
		</div>
		<!-- End: MAIN CONTENT -->

		<%= render :partial => "shared/footer" %>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="contactapp">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Bootbusiness | Short description about company">
		<meta name="author" content="Your name">
		<title>MyFirstApp</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render :partial => "shared/header" %>

		<!-- Start: MAIN CONTENT -->
		<div class="content">
			<%= yield %>
		</div>
		<!-- End: MAIN CONTENT -->

		<%= render :partial => "shared/footer" %>
	</body>
</html>

app/views/shared/_footer.html.erb
<!-- Start: FOOTER -->
<footer>
	<div class="container">
		<div class="row">
			<div class="span2">
				<h4><i class="icon-star icon-white"></i> Products</h4>
				<nav>
					<ul class="quick-links">
						<li>
							<a href="product.html">Product1</a>
						</li>
						<li>
							<a href="product.html">Product2</a>
						</li>
						<li>
							<a href="product.html">Product3</a>
						</li>
						<li>
							<a href="all_products.html">All products</a>
						</li>
					</ul>
				</nav>
				<h4><i class="icon-cogs icon-white"></i> Services</h4>
				<nav>
					<ul class="quick-links">
						<li>
							<a href="service.html">Service1</a>
						</li>
						<li>
							<a href="service.html">Service2</a>
						</li>
						<li>
							<a href="service.html">Service3</a>
						</li>
						<li>
							<a href="all_services.html">All services</a>
						</li>
					</ul>
				</nav>
			</div>
			<div class="span2">
				<h4><i class="icon-beaker icon-white"></i> About</h4>
				<nav>
					<ul class="quick-links">
						<li>
							<a href="our_works.html">Our works</a>
						</li>
						<li>
							<a href="patnerships.html">Patnerships</a>
						</li>
						<li>
							<a href="leadership.html">Leadership</a>
						</li>
						<li>
							<a href="news.html">News</a>
						</li>
						<li>
							<a href="events.html">Events</a>
						</li>
						<li>
							<a href="blog.html">Blog</a>
						</li>
						<ul>
				</nav>
			</div>
			<div class="span2">
				<h4><i class="icon-thumbs-up icon-white"></i> Support</h4>
				<nav>
					<ul class="quick-links">
						<li>
							<a href="faq.html">FAQ</a>
						</li>
						<li>
							<a href="contact_us.html">Contact us</a>
						</li>
					</ul>
				</nav>
				<h4><i class="icon-legal icon-white"></i> Legal</h4>
				<nav>
					<ul class="quick-links">
						<li>
							<a href="#">License</a>
						</li>
						<li>
							<a href="#">Terms of Use</a>
						</li>
						<li>
							<a href="#">Privacy Policy</a>
						</li>
						<li>
							<a href="#">Security</a>
						</li>
					</ul>
				</nav>
			</div>
			<div class="span3">
				<h4>Get in touch</h4>
				<div class="social-icons-row">
					<a href="#"><i class="icon-twitter"></i></a>
					<a href="#"><i class="icon-facebook"></i></a>
					<a href="#"><i class="icon-linkedin"></i></a>
				</div>
				<div class="social-icons-row">
					<a href="#"><i class="icon-google-plus"></i></a>
					<a href="#"><i class="icon-github"></i></a>
					<a href="mailto:soundar.rathinasamy@gmail.com"><i class="icon-envelope"></i></a>
				</div>
				<div class="social-icons-row">
					<i class="icon-phone icon-large phone-number"></i> +919750227877
				</div>
			</div>
			<div class="span3">
				<h4>Get updated by email</h4>
				<form>
					<input type="text" name="email" placeholder="Email address">
					<input type="submit" class="btn btn-primary" value="Subscribe">
				</form>
			</div>
		</div>
	</div>
	<hr class="footer-divider">
	<div class="container">
		<p>
			&copy; 2012-3000 Bootbusiness, Inc. All Rights Reserved.
		</p>
	</div>
</footer>
<!-- End: FOOTER -->

app/views/shared/_header.html.erb
<!-- Start: HEADER -->
<header>
	<!-- Start: Navigation wrapper -->
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="index.html" class="brand brand-bootbus">Bitla</a>
				<!-- Below button used for responsive navigation -->
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<!-- Start: Primary navigation -->
				<div class="nav-collapse collapse">
					<ul class="nav pull-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Products and Services<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li class="nav-header">
									PRODUCTS
								</li>
								<li>
									<a href="product.html">Product1</a>
								</li>
								<li>
									<a href="product.html">Product2</a>
								</li>
								<li>
									<a href="product.html">Product3</a>
								</li>
								<li>
									<a href="all_products.html">All products</a>
								</li>
								<li class="divider"></li>
								<li class="nav-header">
									SERVICES
								</li>
								<li>
									<a href="service.html">Service1</a>
								</li>
								<li>
									<a href="service.html">Service2</a>
								</li>
								<li>
									<a href="service.html">Service3</a>
								</li>
								<li>
									<a href="all_services.html">All services</a>
								</li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<a href="our_works.html">Our works</a>
								</li>
								<li>
									<a href="patnerships.html">Parnerships</a>
								</li>
								<li>
									<a href="leadership.html">Leadership</a>
								</li>
								<li>
									<a href="news.html">News</a>
								</li>
								<li>
									<a href="events.html">Events</a>
								</li>
								<li>
									<a href="blog.html">Blog</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="faq.html">FAQ</a>
						</li>
						<li>
							<a href="contact_us.html">Contact us</a>
						</li>
						<% unless user_signed_in? %>
						<li>
							<%= link_to "Sign up", new_user_registration_path %>
						</li>
						<li>
							<%= link_to "Sign in", new_user_session_path %>
						</li>
						<% else %>
						<li>
							<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
						</li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- End: Navigation wrapper -->
</header>
<!-- End: HEADER -->